In [6]:
import tensorflow as tf

In [7]:
print(tf.__version__)

2.19.0


In [27]:
#Initialization of Tensors

#Manual Initialization
x = tf.constant(4, shape=(1,1),dtype=tf.float32) #specify shape and data type
x = tf.constant([[1,2,3],[4,5,6]])

#3x3 Matrix with values of ones
x= tf.ones((3,3))
x = tf.zeros((2,3))

#I for the identity matrix *eye* (1's in diagonal 0's everywhere else)
x = tf.eye(3) 

#Standard Normal Distribution (3,3): Matrix
x = tf.random.normal((3,3), mean=0, stddev=1)

#Uniform Distribution (1,3): Vector
x = tf.random.uniform((1,3), minval=0, maxval=1)

#Initialize using Range method (Vector)
x = tf.range(start=1, limit=10, delta=2) # behaves exactly like range with differnt named parameters.

#Cast to different dtypes tf.float, tf.int, tf.bool
x = tf.cast(x, dtype=tf.float64)

print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [41]:
#Mathematical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

#operates element wise
z = tf.add(x,y)
z = x + y

z = tf.subtract(x,y)
z = x - y

z = tf.divide(x,y)
z = x/y

z = tf.multiply(x,y)
z = x*y

#Dot Product: sums the product of each column product
z = tf.tensordot(x,y, axes=1)
z = tf.reduce_sum(x*y,axis=0)

#exponentian 
z = x ** 5

#Matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
z = x @ y
print(z)

tf.Tensor(
[[-0.01766162  3.828584    1.3611789   0.54579276]
 [-1.6232768  -0.3390254  -0.65410167 -2.5054176 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.01766162  3.828584    1.3611789   0.54579276]
 [-1.6232768  -0.3390254  -0.65410167 -2.5054176 ]], shape=(2, 4), dtype=float32)


In [48]:
#Indexing Vectors
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:]) #print all elements
print(x[1:])
print(x[::2]) #skip elements by 2
print(x[::-1]) #print in reverse order

#specify indices; extraction
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

#Indexing Matrices

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#Print only first row
print(x[0]) 
print(x[0,:]) # when adding multiple dimension of a tensor seperate values by a comma
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [54]:
#Reshaping
x = tf.range(9) # initially a vector
print(x)

x = tf.reshape(x, (3,3)) # now a matrix
print(x)

#transpose using perm=[]: swaps axis, 1st Row --> 1st Column 2nd Row --> 2nd Column, etc
x = tf.transpose(x, perm=[1,0])
print(x)


tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
